### ISSUE TITLE
[Style] Make Torch Effect Login Form component responsive

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Beautiify#1421] opened 2024-12-23 04:47 UTC
### We need to improve the responsiveness of `Torch Effect Login Form` component for every screen sizes properly.

![image](https://github.com/user-attachments/assets/3f75d5f5-28dc-4bb6-9179-21911c09459c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by dpgaharwal** [comment] 2024-12-28 14:28
As the issue is opened and no one is assigned to it?
Can you please assign to me.

**Comment by Rakesh9100** [comment] 2024-12-28 18:37
Go ahead @dpgaharwal

**Closed** 2024-12-31 15:29 UTC
Labels: KWOC
